# navigation
[nav]
guide = "Guide"
docs = "Docs"
api = "API"
news = "News"

# about post
[post]
list = "All Posts"
archive = "Archives"
tag = "Tags"
readmore = "Read More"

# about pagination
[pager]
prev = "Prev"
next = "Next"

[page]
index = "Index"