# navigation
[nav]
home = "文章"
archive = "归档"
about = "关于"

# about post
[post]
list = "All Posts"
archive = "Archives"
tag = "Tags"
readmore = "Read More"

# about pagination
[pager]
prev = "Prev"
next = "Next"

[page]
index = "Index"