# navigation
[nav]
guide = "快速入门"
docs = "文档"
api = "API"
news = "新闻"

# about post
[post]
list = "所有文章"
archive = "归档"
tag = "标签"
readmore = "阅读更多"

# about pagination
[pager]
prev = "以前的"
next = "更新的"

[page]
index = "目录"